Script started on Fri 24 Feb 2017 03:51:32 AM EST
]0;vagrant@cs61-appliance: ~vagrant@cs61-appliance:~$ cd ~/cs161/root
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ sys161 kernel
sys161: System/161 release 2.0.8, compiled Mar  2 2016 15:46:03

OS/161 base system version 2.0.3
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

 _____           _       ___  ____
|_   _|_ _ _ __ (_)_ __ / _ \/ ___|
  | |/ _` | '_ \| | '__| | | \___ \
  | | (_| | |_) | | |  | |_| |___) |
  |_|\__,_| .__/|_|_|   \___/|____/
          |_|
         _,.,.__,--.__,-----.
      ,""   '))              `.
    ,'   e                    ))
   (  .='__,                  ,
    `~`     `-\  /._____,/   /
             | | )    (  (   ;
             | | |    / / / /
     vvVVvvVvVVVvvVVVvvVVvVvvvV
TapirOS system version ta.pi.r (ASST2 #272)

3876k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 2048; max size 1024k
OS/161 kernel [? for menu]: s
/bin/sh: Timing enabled.
OS/161$ cp -r test1.tes x  xt test2.txt
cp: Usage: cp OLDFILE NEWFILE
/bin/sh: subprocess time: 0.142572325 seconds
Exit 1
OS/161$ cp test1.txt test2.txt
/bin/sh: subprocess time: 0.227941319 seconds
OS/161$ p /sbin/poweroff/  <return>
/bin/sh: p: No such file or directory
/bin/sh: subprocess time: 0.068582141 seconds
Exit 1
OS/161$ exit
Operation took 33.321735251 seconds
OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Shutting down.
The system is halted.
sys161: 1156119634 cycles (86228415 run, 1069891219 global-idle)
sys161:   cpu0: 10883778 kern, 37801 user, 0 idle; 23013 ll, 23013/0 sc, 104269 sync
sys161: 1785 irqs 1521 exns 0r/0w disk 116r/1553w console 47r/11w/13m emufs 0r/0w net
sys161: Elapsed real time: 40.056192 seconds (28.8624 mhz)
sys161: Elapsed virtual time: 43.236805727 seconds (25 mhz)
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ exit
exit

Script done on Fri 24 Feb 2017 03:52:20 AM EST
