Script started on Fri 24 Feb 2017 03:27:51 AM EST
]0;vagrant@cs61-appliance: ~vagrant@cs61-appliance:~$ cd ~/cs161/root
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ sys161 kernel
sys161: System/161 release 2.0.8, compiled Mar  2 2016 15:46:03

OS/161 base system version 2.0.3
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

 _____           _       ___  ____
|_   _|_ _ _ __ (_)_ __ / _ \/ ___|
  | |/ _` | '_ \| | '__| | | \___ \
  | | (_| | |_) | | |  | |_| |___) |
  |_|\__,_| .__/|_|_|   \___/|____/
           |_|
         _,.,.__,--.__,-----.
      ,""   '))              `.
    ,'   e                    ))
   (  .='__,                  ,
    `~`     `-\  /._____,/   /
             | | )    (  (   ;
             | | |    / / / /
     vvVVvvVvVVVvvVVVvvVVvVvvvV
TapirOS system version ta.pi.r (ASST2 #271)

3876k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 2048; max size 1024k
OS/161 kernel [? for menu]: pwd
emu0:
Operation took 0.011961080 seconds
OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Shutting down.
The system is halted.
sys161: 452733997 cycles (59526388 run, 393207609 global-idle)
sys161:   cpu0: 5325278 kern, 19 user, 0 idle; 13433 ll, 13433/0 sc, 87710 sync
sys161: 1205 irqs 5 exns 0r/0w disk 30r/1172w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 13.777591 seconds (32.8602 mhz)
sys161: Elapsed virtual time: 15.945606520 seconds (25 mhz)
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ exit
exit

Script done on Fri 24 Feb 2017 03:28:13 AM EST
