Script started on Fri 24 Feb 2017 03:21:23 AM EST
]0;vagrant@cs61-appliance: ~vagrant@cs61-appliance:~$ cd ~/cs161/root
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ sys161 kernel
sys161: System/161 release 2.0.8, compiled Mar  2 2016 15:46:03

OS/161 base system version 2.0.3
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

 _____           _       ___  ____
|_   _|_ _ _ __ (_)_ __ / _ \/ ___|
  | |/ _` | '_ \| | '__| | | \___ \
  | | (_| | |_) | | |  | |_| |___) |
  |_|\__,_| .__/|_|_|   \___/|____/
           |_|
         _,.,.__,--.__,-----.
      ,""   '))              `.
    ,'   e                    ))
   (  .='__,                  ,
    `~`     `-\  /._____,/   /
             | | )    (  (   ;
             | | |    / / / /
     vvVVvvVvVVVvvVVVvvVVvVvvvV
TapirOS system version ta.pi.r (ASST2 #271)

3876k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 2048; max size 1024k
OS/161 kernel [? for menu]: tt2
Starting thread test 2...
0123456701234567
Thread test 2 done.
Operation took 0.675931280 seconds
OS/161 kernel [? for menu]: p /sbin/poweroff<  <return>
Shutting down.
The system is halted.
sys161: 469634900 cycles (76825780 run, 392809120 global-idle)
sys161:   cpu0: 20009100 kern, 19 user, 0 idle; 14332 ll, 14332/0 sc, 89890 sync
sys161: 1329 irqs 5 exns 0r/0w disk 32r/1233w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 14.176242 seconds (33.1283 mhz)
sys161: Elapsed virtual time: 16.517020227 seconds (25 mhz)
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ exit
exit

Script done on Fri 24 Feb 2017 03:22:07 AM EST
