Script started on Fri 24 Feb 2017 03:23:54 AM EST
]0;vagrant@cs61-appliance: ~vagrant@cs61-appliance:~$ cd ~/cs161/root
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ sys161 kernel
sys161: System/161 release 2.0.8, compiled Mar  2 2016 15:46:03

OS/161 base system version 2.0.3
Copyright (c) 2000, 2001-2005, 2008-2011, 2013, 2014
   President and Fellows of Harvard College.  All rights reserved.

 _____           _       ___  ____
|_   _|_ _ _ __ (_)_ __ / _ \/ ___|
  | |/ _` | '_ \| | '__| | | \___ \
  | | (_| | |_) | | |  | |_| |___) |
  |_|\__,_| .__/|_|_|   \___/|____/
           |_|
         _,.,.__,--.__,-----.
      ,""   '))              `.
    ,'   e                    ))
   (  .='__,                  ,
    `~`     `-\  /._____,/   /
             | | )    (  (   ;
             | | |    / / / /
     vvVVvvVvVVVvvVVVvvVVvVvvvV
TapirOS system version ta.pi.r (ASST2 #271)

3876k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lhd0 at lamebus0
lhd1 at lamebus0
lser0 at lamebus0
con0 at lser0

cpu0: MIPS/161 (System/161 2.x) features 0x0
buffers: max count 2048; max size 1024k
OS/161 kernel [? for menu]: tt3
Starting thread test 3 (5 [sleepalots], 2 {computes}, 1 waker)
[3]{1: 227}{0: 171}[3][4][1][0][2]{1: 127}{0: 31}[3][2][4][0][1]{1: 207}{0: 188}[3][4][2][3]{1: 143}{0: 5}[0][1][4][3][2]{1: 93}{0: 123}[1][4][0]{1: 168}{0: 249}[2][3][1][4]{1: 135}{0: 52}[2][0]{1: 12}[1][3]{0: 224}[4][2]{1: 56}[0]{0: 129}[1]{1: 25}[3][4]{0: 225}[4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][3][0][4][2][1][0][2][1][0][0]
Thread test 3 done
Operation took 6.609929360 seconds
OS/161 kernel [? for menu]: p s /sbinb /poweroff <return>
Shutting down.
The system is halted.
sys161: 508736248 cycles (223795664 run, 284940584 global-idle)
sys161:   cpu0: 167392743 kern, 19 user, 0 idle; 51688 ll, 51688/0 sc, 232830 sync
sys161: 2401 irqs 5 exns 0r/0w disk 34r/1709w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 14.590502 seconds (34.8676 mhz)
sys161: Elapsed virtual time: 18.097624213 seconds (25 mhz)
]0;vagrant@cs61-appliance: ~/cs161/rootvagrant@cs61-appliance:~/cs161/root$ exit
exit

Script done on Fri 24 Feb 2017 03:24:22 AM EST
